# mostly inspired with:
# https://github.com/hyprwm/hyprlock/blob/main/assets/example.conf

source=~/.config/hypr/hyprlock/colors.conf

$font = Noto Sans

background {
    monitor =
    path = screenshot
    blur_passes = 5
}

input-field {
    monitor =
    size = 17.5%, 5%
    outline_thickness = 2

    inner_color = rgb(200, 200, 200)
    outer_color = rgb(15, 15, 15)
    fail_color = rgba(ff6633ee) rgba(ff0066ee) 40deg
    font_color = rgb(10, 10, 10)

    dots_size = 0.4
    dots_spacing = 0.3
    dots_center = true

    hide_input = false
    placeholder_text = Input Password...
    fail_text = 

    position = 0, -20
    halign = center
    valign = center
}

# greeting
label {
    monitor =

    text = Hi, $USER!
    color = rgba(200, 200, 200, 1.0)
    font_size = 50
    font_family = $font

    position = 0, 25%
    halign = center
    valign = center
}

# date
label {
    monitor =

    text = cmd[update:60000] date +"%a, %d %b" # update every 60 seconds
    color = rgba(200, 200, 200, 1.0)
    font_size = 25
    font_family = $font

    position = 0, 10%
    halign = center
    valign = center
}

# time
label {
    monitor =

    text = $TIME
    color = rgba(200, 200, 200, 1.0)
    font_size = 25
    font_family = $font

    position = 0, 5%
    halign = center
    valign = center
}

# keyboard layout
label {
    monitor =

    text = $LAYOUT
    onclick = hyprctl switchxkblayout all next
    color = rgba(200, 200, 200, 1.0)
    font_size = 25
    font_family = $font

    position = -2.5%, 2.5%
    halign = right
    valign = bottom
}
